import {readFile,mkdir,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
export function validLevel(level){return level===null||(Number.isInteger(level)&&level>=1&&level<=6);}
export async function readLesson(root,key){try{const data=JSON.parse(await readFile(path.join(root,'lesson-settings',key+'.json'),'utf8'));if(!validLevel(data.level)||(data.restart&&!/^[a-f0-9-]{36}$/.test(data.restart)))throw new Error('Invalid lesson settings.');return data;}catch(e){if(e.code==='ENOENT')return {level:null,restart:null};throw e;}}
export async function writeLesson(root,key,data){const dir=path.join(root,'lesson-settings');await mkdir(dir,{recursive:true});const file=path.join(dir,key+'.json'),temp=file+'.'+randomUUID()+'.tmp';await writeFile(temp,JSON.stringify(data));await rename(temp,file);}
export function lessonInstructions(topic,level){
 const difficulty=level===null?'Use the shared learner profile as the initial difficulty, then adapt to answers.':`The learner selected TOPIK ${level} as the practice difficulty for THIS topic. Use that level as an approximate exercise target, not a certified assessment or a claim that this grammar belongs exclusively to that level. This explicit selection overrides the profile baseline for exercise difficulty.`;
 const anchors={1:'Short everyday sentences, common concrete vocabulary, one clause.',2:'Familiar daily situations, short connected sentences, common endings.',3:'Everyday and familiar work/study contexts, moderate clause complexity and common contrasts.',4:'More nuanced everyday and work situations, several related clauses, natural collocations and register.',5:'Abstract and professional contexts, implicit relationships, subtle usage contrasts and varied register.',6:'Complex abstract contexts, precise nuance, idiomatic phrasing and fine distinctions; use natural language rather than obscure trivia.'};
 const format=/^(grammar|vocabulary)$/i.test(topic.category)?`GRAMMAR/VOCABULARY LESSON SEQUENCE (takes precedence over earlier generic exercise instructions):
1. Start a fresh lesson with a clear explanation in Korean: core meaning, attachment/use rules, common natural uses, important contrasts, and a few examples. Research reliable sources as needed. Then present multiple-choice question 1 of 6 in the SAME first reply.
2. Ask SIX multiple-choice questions about correct use in a specific context, ONE question per turn. Label them 객관식 1/6 through 객관식 6/6. Provide four choices A–D with exactly one defensible best answer; supply enough context to resolve ambiguity. Vary the correct letter. Do not reveal the answer until the learner responds. Accept a letter or the choice text. After each response explain the correct usage and why the selected wrong option fails, then ask the next question. Treat clarification questions as clarifications, not completed answers. Avoid cumulative scores. For vocabulary include collocations, word senses, register and near-synonyms; for grammar include attachment, meaning and pragmatic fit.
3. After answering question 6, move to English-to-Korean translation practice. Give ONE English sentence at a time and wait for the learner's Korean attempt. English exercise sentences are an explicit exception to the Korean-only reply rule. All explanations, feedback and directions remain Korean. Do NOT supply the Korean answer before an attempt. Vary subjects, situations, tense, sentence structure and register at the selected difficulty while keeping this topic central.
4. Correct each attempt: quote the learner's wording, offer a natural Korean version, explain the specific issue in Korean, and distinguish a valid alternative from a genuine error. Acknowledge an already natural answer without inventing corrections. Then provide the next varied English sentence. Continue until the learner stops or changes the task. No time targets or scores.
Track which phase and question you are on from this conversation; resume from that point. Changing difficulty changes subsequent questions without resetting the phase. Only a new conversation starts again at the explanation. If an existing conversation predates this format and has no multiple-choice sequence, briefly bridge from the prior explanation and start question 1/6. Honor explicit learner requests to skip, repeat, or revisit a phase.`:'For this non-grammar/non-vocabulary topic, keep its existing topic-appropriate teaching format.';
 const detours=`SIDE QUESTIONS: Answer the learner's Korean-language questions even when unrelated to the current lesson. Do not refuse or postpone them just to enforce the sequence. Give a useful answer in Korean at the selected difficulty, researching uncertain usage when needed. Preserve the paused phase, question number, choices, or pending English sentence. After answering, add a short, natural transition and restate the same pending exercise without revealing its answer. Do not count a side question as an attempt, advance the question number, grade it as wrong, or restart the lesson. If they ask another side question, answer that too and return to the same saved point; there is no limit on detours. If one message contains BOTH a genuine exercise answer and a side question, address both, then continue from the next appropriate exercise. If the learner explicitly asks to pause or abandon the lesson, respect that rather than repeatedly redirecting.`;
 return `${detours}\n${difficulty}\n${level?anchors[level]:''}\n${format}`;
}
